'use client';

import { useState } from 'react';
import { Loader2, RefreshCw, FileText, AlertTriangle } from 'lucide-react';
import { formatDateTime } from '@/lib/utils';
import MarkdownContent from '@/components/ui/MarkdownContent';

interface Props {
  matterId: string;
  initialContent: string | null;
  initialGeneratedAt: string | null;
  entryCount: number;
}

export default function SummaryViewer({ matterId, initialContent, initialGeneratedAt, entryCount }: Props) {
  const [content, setContent] = useState(initialContent);
  const [generatedAt, setGeneratedAt] = useState(initialGeneratedAt);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  async function generate() {
    setLoading(true);
    setError('');
    try {
      const res = await fetch('/api/summary/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ matterId }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error);
      setContent(data.summary.content);
      setGeneratedAt(data.summary.generatedAt);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to generate summary');
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="bg-white rounded-xl border border-slate-200 p-5">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="font-semibold text-slate-900">Case Summary & Causation Analysis</h2>
            {generatedAt && (
              <p className="text-xs text-slate-500 mt-0.5">Generated {formatDateTime(generatedAt)}</p>
            )}
          </div>
          <button
            onClick={generate}
            disabled={loading || entryCount === 0}
            className="flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-700 disabled:bg-blue-300 text-white text-sm font-medium rounded-lg transition-colors"
          >
            {loading ? (
              <><Loader2 className="w-4 h-4 animate-spin" /> Generating…</>
            ) : content ? (
              <><RefreshCw className="w-4 h-4" /> Regenerate</>
            ) : (
              <><FileText className="w-4 h-4" /> Generate Summary</>
            )}
          </button>
        </div>

        {entryCount === 0 && (
          <div className="mt-3 flex items-start gap-2 p-3 bg-amber-50 border border-amber-200 rounded-lg">
            <AlertTriangle className="w-4 h-4 text-amber-600 mt-0.5 flex-shrink-0" />
            <p className="text-sm text-amber-700">No chronology entries found. Please upload documents and generate a chronology first.</p>
          </div>
        )}

        {error && (
          <div className="mt-3 p-3 bg-red-50 border border-red-200 rounded-lg text-red-700 text-sm">{error}</div>
        )}
      </div>

      {/* AI disclaimer */}
      <div className="bg-amber-50 border border-amber-200 rounded-xl px-4 py-2.5">
        <p className="text-xs text-amber-800">
          <strong>AI-Generated — Review Required.</strong> This summary is generated by AI and must be reviewed and verified by a qualified solicitor before use in proceedings, correspondence, or instructions to counsel.
        </p>
      </div>

      {/* Summary content */}
      {content ? (
        <div className="bg-white rounded-xl border border-slate-200 p-6">
          <MarkdownContent text={content} className="space-y-1.5" />
        </div>
      ) : !loading && (
        <div className="bg-white rounded-xl border border-slate-200 p-10 text-center">
          <FileText className="w-10 h-10 text-slate-300 mx-auto mb-3" />
          <p className="text-slate-500 text-sm">No case summary generated yet.</p>
          <p className="text-slate-400 text-xs mt-1">Click &quot;Generate Summary&quot; to create a barrister-ready case summary.</p>
        </div>
      )}

      {loading && (
        <div className="bg-white rounded-xl border border-slate-200 p-10 text-center">
          <Loader2 className="w-8 h-8 text-blue-500 animate-spin mx-auto mb-3" />
          <p className="text-slate-600 text-sm">Generating case summary…</p>
          <p className="text-slate-400 text-xs mt-1">Analysing {entryCount} chronology entries. This may take 30–60 seconds.</p>
        </div>
      )}
    </div>
  );
}
