'use client';

import { useState } from 'react';
import { Download, FileText, CheckCircle, AlertTriangle, Loader2 } from 'lucide-react';

interface Props {
  matterId: string;
  docCount: number;
  entryCount: number;
  verifiedCount: number;
  hasSummary: boolean;
}

export default function BundleBuilder({ matterId, docCount, entryCount, verifiedCount, hasSummary }: Props) {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const readyChecks = [
    { label: 'Documents uploaded', ok: docCount > 0, value: `${docCount} document${docCount !== 1 ? 's' : ''}` },
    { label: 'Chronology generated', ok: entryCount > 0, value: `${entryCount} entries` },
    { label: 'Entries verified', ok: verifiedCount > 0, value: `${verifiedCount} of ${entryCount} verified` },
    { label: 'Case summary', ok: hasSummary, value: hasSummary ? 'Generated' : 'Not generated (optional)' },
  ];

  async function downloadBundle() {
    setLoading(true);
    setError('');
    try {
      const res = await fetch('/api/bundle/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ matterId }),
      });

      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error || 'Failed to generate bundle');
      }

      const html = await res.text();
      const blob = new Blob([html], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `bundle-${matterId}.html`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to generate bundle');
    } finally {
      setLoading(false);
    }
  }

  const canGenerate = docCount > 0 && entryCount > 0;

  return (
    <div className="max-w-2xl space-y-5">
      {/* Bundle readiness */}
      <div className="bg-white rounded-xl border border-slate-200 p-5">
        <h2 className="font-semibold text-slate-900 mb-4">Bundle Readiness</h2>
        <div className="space-y-3">
          {readyChecks.map(({ label, ok, value }) => (
            <div key={label} className="flex items-center gap-3">
              {ok ? (
                <CheckCircle className="w-5 h-5 text-green-500 flex-shrink-0" />
              ) : (
                <AlertTriangle className="w-5 h-5 text-amber-500 flex-shrink-0" />
              )}
              <div className="flex-1">
                <span className="text-sm font-medium text-slate-900">{label}</span>
              </div>
              <span className={`text-sm ${ok ? 'text-green-700' : 'text-amber-700'}`}>{value}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Bundle contents */}
      <div className="bg-white rounded-xl border border-slate-200 p-5">
        <h2 className="font-semibold text-slate-900 mb-4">Bundle Contents</h2>
        <div className="space-y-2">
          {[
            { section: 'Cover Page', desc: 'Matter reference, client details, date prepared' },
            { section: 'Table of Contents', desc: 'Auto-generated with bundle statistics' },
            { section: 'Section 1 — Case Summary', desc: hasSummary ? 'AI-generated causation analysis' : 'Not yet generated' },
            { section: 'Section 2 — Full Chronology', desc: `${entryCount} entries, colour-coded by relevance` },
            { section: 'Section 3 — Document Index', desc: `${docCount} source documents indexed` },
          ].map(({ section, desc }) => (
            <div key={section} className="flex items-start gap-3 p-2">
              <FileText className="w-4 h-4 text-blue-500 mt-0.5 flex-shrink-0" />
              <div>
                <p className="text-sm font-medium text-slate-900">{section}</p>
                <p className="text-xs text-slate-500">{desc}</p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Compliance notice */}
      <div className="bg-amber-50 border border-amber-200 rounded-xl p-4">
        <p className="text-xs text-amber-800 leading-relaxed">
          <strong>Important:</strong> This bundle is generated by AI and marked &quot;AI-Generated — Review Required&quot;. All entries must be verified by a qualified fee earner before the bundle is disclosed to counsel or used in proceedings. The bundle is produced in HTML format — print to PDF using your browser for a final barrister-ready document.
        </p>
      </div>

      {error && (
        <div className="p-3 bg-red-50 border border-red-200 rounded-lg text-red-700 text-sm">{error}</div>
      )}

      <button
        onClick={downloadBundle}
        disabled={loading || !canGenerate}
        className="flex items-center gap-2 px-5 py-3 bg-blue-600 hover:bg-blue-700 disabled:bg-slate-300 text-white font-medium rounded-xl transition-colors text-sm"
      >
        {loading ? (
          <><Loader2 className="w-4 h-4 animate-spin" /> Generating Bundle…</>
        ) : (
          <><Download className="w-4 h-4" /> Download Barrister Bundle (HTML)</>
        )}
      </button>

      {!canGenerate && (
        <p className="text-xs text-slate-500">Upload documents and generate a chronology before downloading the bundle.</p>
      )}
    </div>
  );
}
